
-- --------------------------------------------------------

--
-- Table structure for table `mumbaiuniversity`
--

CREATE TABLE `mumbaiuniversity` (
  `Name` varchar(50) NOT NULL,
  `Collegename` varchar(50) NOT NULL,
  `Departmentname` varchar(50) NOT NULL,
  `Qualification` varchar(50) NOT NULL,
  `Areaofinterest` varchar(50) NOT NULL,
  `Designation` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `mumbaiuniversity`
--

INSERT INTO `mumbaiuniversity` (`Name`, `Collegename`, `Departmentname`, `Qualification`, `Areaofinterest`, `Designation`) VALUES
('Disha Bhosle', 'Atharva College of Engineering', 'Electronics Engineering', 'M.E(Elex)', '', 'Head of Department'),
('Prajakta Borole', 'Atharva College of Engineering', 'Electrical Engineering', 'M.E(Extc)', '', 'Assistant Professor'),
('Namrata Lade', 'Atharva College of Engineering', 'Electronics Engineering', 'M.Tech(Extc)', '', ''),
('Samuel Jacob', 'Atharva College of Engineering', 'Electronics Engineering', 'M.E(Extc)', '', ''),
('Mahendra Patel', 'Atharva College of Engineering', 'Computer Technology', 'ME(IT)', '', 'Head of Department'),
('Shweta Sharma', 'Atharva College of Engineering', 'Computer Technology', 'M.E(Comps)', '', 'Assistant Professor'),
('Neha Singh', 'Atharva College of Engineering', 'Computer Technology', 'Mtech(CS)', '', 'Assistant Professor'),
('Amrutha Sankhe', 'Atharva College of Engineering', 'Computer Technology', 'M.E(Comps)', '', 'Assistant Professor'),
('Nileema Pathak', 'Atharva College of Engineering', 'Information Technology', 'B.E,M.E(Extc)', '', 'Head of Department'),
('Chanda  Chouhan', 'Atharva College of Engineering', 'Information Technology', 'M.E(Comps)', '', 'Assistant Professor'),
('Vaishali Salvi', 'Atharva College of Engineering', 'Information Technology', 'M.E(IT)', '', 'Assistant Professor'),
('Renuka Nagpure', 'Atharva College of Engineering', 'Information Technology', 'M.E (C.S)', '', 'Assistant Professor'),
('Jyoti Kolap', 'Atharva College of Engineering', 'Electronics and Telecommunications', 'M.E(Extc)', '', 'Head of Department'),
('Mohan Kumar', 'Atharva College of Engineering', 'Electronics and Telecommunications', 'M.E(Elex)', '', 'Assistant Professor'),
('Gauri Salunkhe', 'Atharva College of Engineering', 'Electronics and Telecommunication', 'M.E(Elex)', '', 'Assistant Professor'),
('Jyoti Mali', 'Atharva College of Engineering', 'Electronics and Telecommunications', 'M.E(Extc)', '', 'Assistant Professor'),
('Dr  Kavita Sonawane', 'St.Francis College of Engineering', 'Computer Technology', 'P.HD', '', 'Head of Department'),
('Rajkumar Shende', 'St.Francis College of Engineering', 'Computer Technology', 'M.E(IT)', '', 'Assistant Professor'),
('Bidhisha Roy', 'St.Francis College of Engineering', 'Computer Technology', 'Mtech(CS)', '', 'Assistant Professor'),
('Vincy Joseph', 'St.Francis College of Engineering', 'Computer Technology', 'B.E(Extc)', '', 'Assistant Professor'),
('Dr Gautam Shah', 'St.Francis College of Engineering', 'Electronics and ', '', '', ''),
('Dr.Gautam Shah', 'St.Francis College of Engineering', 'Electronics and Telecommunication', 'M.E(Elex)', '', 'Head of Department'),
('Dr Kevin Noronha', 'St.Francis College of Engineering', 'Electronics and Telecommunications', 'P.HD', '', 'Assistant Professor'),
('Anjali Chaudhari', 'St.Francis College of Engineering', 'Electronics and Telecommunication', 'M.E,B.E(Extc)', '', 'Assistant Professor'),
('Monika Cheema', 'St.Francis College of Engineering', 'Electronics and Telecommunications', 'M.E(Extc)', '', 'Assistant Professor'),
('Gauri Salunkhe', 'Atharva College of Engineering', 'Electronics and Telecommunications', 'M.Tech(Extc)', '', 'Assistant Professor'),
('Dr. Gautam Shah', 'St. Francis College of Engineering', 'Electronics and Telecommunications', 'P.HD', '', 'Head of Department'),
('Dr. Joanne Gomes', 'St.Francis College of Engineering', 'Information Technology', 'B.E,M.E(Extc)', '', 'Head of Department'),
('Nazneen Ansari', 'St.Francis College of Engineering', 'Information Technology', 'M.E(IT)', '', 'Assistant Professor'),
('Mrinal Lopes', 'St.Francis College of Engineering', 'Information Technology', 'M.E(Elex)', '', 'Assistant Professor'),
('Amrita Mathur', 'St.Francis College of Engineering', 'Information Technology', 'M.E (C.S)', '', 'Assistant Professor'),
('Dr.BB Mesharam', 'VJTI', 'Electrical Engineering', 'P.HD', '', 'Head of Department'),
('kjbhj', 'hjvb', 'hjvb', 'ugvu', 'ugvu', 'Head of Department'),
('Dr.BB Mesharam', 'Atharva College of Engineering', 'Electrical Engineering', 'P.HD', 'VLSI,Embedded systems', 'Assistant Professor'),
('Dr.Joanne Gomes', 'St.Francis College of Engineering', 'Information Technology', 'P.HD', '', 'Head of Department'),
('Nazneen Ansari', 'St.Francis College of Engineering', 'Information Technology', 'M.E (C.S)', '', 'Assistant Professor'),
('Dr.BB Mesharam', 'Atharva College of Engineering', 'Computer Technology', 'M.E(Elex)', '', 'Head of Department'),
('Nazneen Ansari', 'Atharva College of Engineering', 'Information Technology', 'M.E(Comps)', '', 'Assistant Professor'),
('Mrinal Lopes', 'St.Francis College of Engineering', 'Information Technology', 'M.E(Elex)', '', 'Assistant Professor'),
('Amrita Mathur', 'St.Francis College of Engineering', 'Information Technology', 'M.E (C.S)', '', 'Assistant Professor'),
('D.S.S Sudhakar', 'Fr. Conceicao Rodrigues College of Engineering', 'Production Engineering', 'M.Tech(Mech)', '', 'Head of Department'),
('Dr.V.S.Jorapur', 'Fr. Conceicao Rodrigues College of Engineering', 'Production Engineering', 'P.HD', '', 'Assistant Professor'),
(' Miriyala Veerabhadrarao D.N', 'Fr. Conceicao Rodrigues College of Engineering', 'Production Engineering', 'ME Production Engg.', 'Engineering Mechanics, Engineering Drawing , Indus', 'Assistant Professor'),
(' Anant N.Tarse', 'Fr. Conceicao Rodrigues College of Engineering', 'Production Engineering', 'ME Production Engg. ', ' Computer Aided Machine Drawing, Engineering Mecha', 'Assistant Professor'),
(' Dr. Sunil Surve', 'Fr. Conceicao Rodrigues College of Engineering', 'Computer Technology', 'P.HD', ' Microprocessor, Software Architecture', 'Head of Department'),
(' Brijmohan Daga', 'Fr. Conceicao Rodrigues College of Engineering', 'Computer Technology', 'M.E (CS)', 'Artificial Intelligence, System Security', 'Assistant Professor'),
('Merly Thomas', 'Fr. Conceicao Rodrigues College of Engineering', 'Computer Technology', 'M.E (C.S)', 'Software Engineering , Computer Networks', 'Assistant Professor'),
('Dr. Sujatha Deshmukh', 'Fr. Conceicao Rodrigues College of Engineering', 'Computer Technology', 'P.HD', '', 'Assistant Professor'),
(' Dr. Jagruti Save', 'Fr. Conceicao Rodrigues College of Engineering', 'Information Technology', 'P.HD', 'Database, Data mining', 'Head of Department'),
('Ms. Garima Tripathi', 'Fr. Conceicao Rodrigues College of Engineering', 'Information Technology', 'M.E(ELex)', 'Digital design, Embedded systems', 'Assistant Professor'),
(' Saurabh Keshav Kulkarni', 'Fr. Conceicao Rodrigues College of Engineering', 'Information Technology', 'ME (CS)', 'Web programming, Big data analytics', 'Assistant Professor'),
(' Jay Laxman Borade', 'Fr. Conceicao Rodrigues College of Engineering', 'Information Technology', 'ME (CS)', 'Computer graphics and virtual Reality, Distributed', 'Assistant Professor'),
('Dr. Deepak Bhoir', 'Fr. Conceicao Rodrigues College of Engineering', 'Electronics Engineering', 'P.HD', 'VLSI, Biomedical Engineering', 'Head of Department'),
(' Dr. Sapna U. Prabhu', 'Fr. Conceicao Rodrigues College of Engineering', 'Electronics Engineering', 'P.HD', 'Embedded Systems', 'Assistant Professor'),
(' Vibhav Godbole', 'Fr. Conceicao Rodrigues College of Engineering', 'Electronics Engineering', 'ME (Electronics & Telecommunication)', 'Computer Architecture', 'Assistant Professor'),
('Monica T. Khanore ', 'Fr. Conceicao Rodrigues College of Engineering', 'Electronics Engineering', 'M.E (Elex)', 'Communication Technology', 'Assistant Professor'),
('Dr. Lata Ragha', 'Fr. C. Rodrigues Institute of Techology', 'Computer Technology', 'P.HD', '', 'Head of Department'),
(' M.Kiruthika', 'Fr. C. Rodrigues Institute of Technoloy', 'Computer Technology', 'M.E (C.S)', '', 'Assistant Professor'),
('Dr. Pritha Bhattacharyya', 'Fr. C. Rodrigues Institute of Techology', 'Computer Technology', 'P.HD', '', 'Assistant Professor'),
(' Amroz Siddiqui', 'Fr. C. Rodrigues Institute of Technoloy', 'Computer Technology', 'M.Tech(Mech)', '', 'Assistant Professor'),
('Dr. Hariram Chavan', 'Fr. C. Rodrigues Institute of Techology', 'Information Technology', 'P.HD', '', 'Head of Department'),
(' Lakshmi Gadhikar', 'Fr. C. Rodrigues Institute of Technoloy', 'Information Technology', 'M.Tech(IT)', '', 'Assistant Professor'),
(' Dr. Sanjukta Bhowmik', 'Fr. C. Rodrigues Institute of Techology', 'Information Technology', 'P.HD', '', 'Assistant Professor'),
('Archana Shirke', 'Fr. C. Rodrigues Institute of Technoloy', 'Information Technology', 'M.E (C.S)', '', 'Assistant Professor'),
('Dr. S M Khot', 'Fr. C. Rodrigues Institute of Techology', 'Mechanical Engineering', 'P.HD', '', 'Assistant Professor'),
('Dr. Nilaj Deshmukh', 'Fr. C. Rodrigues Institute of Technoloy', 'Mechanical Engineering', 'P.HD', '', 'Head of Department'),
('Mathewlal Thomas', 'Fr. C. Rodrigues Institute of Techology', 'Mechanical Engineering', 'M.E(Mech)', '', 'Assistant Professor'),
('Dr.Nitesh Prakash Yelve', 'Fr. C. Rodrigues Institute of Technoloy', 'Mechanical Engineering', 'P.HD', '', 'Assistant Professor'),
('Dr. Milind Shah', 'Fr. C. Rodrigues Institute of Techology', 'Electronics and Telecommunications', 'P.HD', '', 'Head of Department'),
('Dr. Ramnath Iyer', 'Fr. C. Rodrigues Institute of Technoloy', 'Electronics and Telecommunications', 'P.HD', '', 'Assistant Professor'),
('Sadhana Pai ', 'Fr. C. Rodrigues Institute of Techology', 'Electronics and Telecommunications', 'M.E(Extc)', '', 'Assistant Professor'),
('Megha Kolhekar ', 'Fr. C. Rodrigues Institute of Technoloy', 'Electronics and Telecommunications', 'M.E(Extc)', '', 'Assistant Professor'),
('Dr. Hari Vasudevan', 'DJ Sanghvi College of Engineering', 'Production Engineering', 'P.HD', '', 'Head of Department'),
(' E. Narayanan', 'DJ Sanghvi College of Engineering', 'Production Engineering', 'M.Tech(Mech)', '', 'Assistant Professor'),
('Dr. Atul Dhale', 'DJ Sanghvi College of Engineering', 'Production Engineering', 'P.HD', '', 'Assistant Professor'),
(' R. S. Khavekar', 'DJ Sanghvi College of Engineering', 'Production Engineering', 'M.E (Mech)', '', 'Assistant Professor'),
('Dr. Prasad S. Joshi', 'DJ Sanghvi College of Engineering', 'Electronics Engineering', 'P.HD', '', 'Head of Department'),
('C. K. Beral', 'DJ Sanghvi College of Engineering', 'Electronics Engineering', 'M.E(Extc)', '', 'Assistant Professor'),
('Sejal  A. Kadam', 'DJ Sanghvi College of Engineering', 'Electronics Engineering', 'M.Tech(Extc)', '', 'Assistant Professor'),
(' Vivek Nar', 'DJ Sanghvi College of Engineering', 'Electronics Engineering', 'M.E(Extc)', '', 'Assistant Professor'),
('Dr. Abhijit R. Joshi', 'DJ Sanghvi College of Engineering', 'Information Technology', 'P.HD', '', 'Head of Department'),
('Suchita Rane', 'DJ Sanghvi College of Engineering', 'Information Technology', 'M.E(Comps)', '', 'Assistant Professor'),
('Amit P. Sahu', 'DJ Sanghvi College of Engineering', 'Information Technology', 'Mtech(CS)', '', 'Assistant Professor'),
('Amruta Patil', 'DJ Sanghvi College of Engineering', 'Information Technology', 'M.E(Comps)', '', 'Assistant Professor'),
('Dr. Narendra  M. Shekokar', 'DJ Sanghvi College of Engineering', 'Computer Technology', 'P.HD', '', 'Head of Department'),
('Dr.  Jyoti  Joglekar', 'DJ Sanghvi College of Engineering', 'Computer Technology', 'P.HD', '', 'Assistant Professor'),
('Dr. Meera  M. Narvekar', 'DJ Sanghvi College of Engineering', 'Computer Technology', 'P.HD', '', 'Assistant Professor'),
('Dr. Ramchandra  Mangrulkar', 'DJ Sanghvi College of Engineering', 'Computer Technology', 'P.HD', '', 'Assistant Professor');
